name: echoverse
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - python-dotenv
      - requests
      - PyPDF2
      - python-docx
      - gtts
      - pydub
      - transformers
